---
all:
  children:
    clickhouse:
      hosts:
        centos7:
          ansible_connection: ssh
          ansible_host: 158.160.18.238
    vector:
      hosts:
        centos7:
          ansible_connection: ssh
          ansible_host: 158.160.18.238
    lighthouse:
      hosts:
        centos7:
          ansible_connection: ssh
          ansible_host: 158.160.18.238
    nginx:
      hosts:
        centos7:
          ansible_connection: ssh
          ansible_host: 158.160.18.238
